name: Deploy on IIS

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    
    defaults:
      run:
        shell: cmd

    steps:
    - uses: actions/checkout@v3
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Stop app pool
      run: net stop MarmitonVanced
    - name: Publish Release
      run: dotnet publish --configuration Release -o C:\inetpub\marmitonVanced
    - name: Start app pool
      run: net start MarmitonVanced
              
